---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен иметь регистрацию пользователя с указанием номера телефона и e-mail
  - Если пользователь не авторизован и не зарегистрирован, при заказате товара должен указываться номер телефона и e-mail для связи
  - Передача данных должна быть организована по протоколу https
  - Пользователь должен иметь возможность обратной связи с магазином
  - Пользователь должен иметь возможность удаления товаров из корзины
  - Пользователь должен иметь возможность фильтровать товары по бренду, цене, наличию
  - После оформления заказа, заказанные товары должны убираться из корзины
  - При переводе языка сайта, все элементы интерфейса должны менять язык
